version: 3
vars:
  REL_CONAN: "build/dependencies/conan"
  CONAN_DIR: |
    {{env "PWD"}}/build/dependencies/conan

tasks:
  conan_install:
    cmds:
      - conan install . -if {{.REL_CONAN}} --build=missing --settings compiler.libcxx="libstdc++11"
    status:
      - test -e {{.CONAN_DIR}}

  main:
    dir: build
    desc: "Build main project"
    deps: [conan_install]
    cmds:
      - cmake ..
      - make -j8
      - cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - ./bin/hcparse -o build/db.sqlite -a -b compile_commands.json
