name: test
on: [push]
jobs:
  compile:
    if: |
      !contains(github.event.head_commit.message, 'SKIP')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'

      - run: sudo apt-get install libclang-dev
      - run: "nimble test -y -d:nimDebugDlOpen"
