name: test
on: [push]
jobs:
  compile:
    if: |
      !contains(github.event.head_commit.message, 'SKIP')
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get -qq update
      - run: apt-get -qq -y install cmake git g++ gcc make sudo tar wget curl xz-utils pip
        env:
          DEBIAN_FRONTEND: noninteractive

      - run: pip install conan
      - run: |
          cd src/hcparse/read_boost_wave
          conan install . --build=missing --settings compiler.libcxx="libstdc++11"
          mkdir build
          cd build
          cmake ..
          make -j8
          cd ..

      - run: |
          wget https://nim-lang.org/choosenim/init.sh
          chmod +x init.sh
          sh init.sh -y

      - run: |
          echo "deb http://apt.llvm.org/hirsute/ llvm-toolchain-hirsute-13 main" > /etc/apt/sources.list.d/llvm-13.list
          apt-get install -y \
            clang-13 \
            clang-tools-13 \
            clang-13-doc \
            libclang-common-13-dev \
            libclang-13-dev \
            libclang1-13 \
            clang-format-13 \
            clangd-13
        env:
          DEBIAN_FRONTEND: noninteractive

      - run: |
          wget "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${TS_VERSION}.tar.gz" && \
          tar -xvf "v${TS_VERSION}.tar.gz" && \
          cd "tree-sitter-${TS_VERSION}" && \
          sudo make install PREFIX=/usr
        env:
          TS_VERSION: "0.20.0"

      - run: |
          export PATH=$HOME/.nimble/bin:$PATH
          echo $PATH
          nimble -y develop

      - shell: bash
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          echo $PATH

          export LD_LIBRARY_PATH=$(pwd)/lib
          cat src/hcparse/read_boost_wave/activate_run.sh
          source src/hcparse/read_boost_wave/activate_run.sh

          echo '--path="$nim"' > nim.cfg
          cat nim.cfg

          nim r tests/runall.nim test $(pwd)/hcparse.nimble
          nim r tests/runall.nim doc $(pwd)/hcparse.nimble --ignore="**/dox*.nim"

      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: htmldocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
